### ISSUE TITLE
Please use a valid license

### ISSUE THREAD

**Issue by mkesper** [ers35/luakernel#1]
In many countries you cannot just disclaim copyright.
It would clarify things if you used something like CC0: http://creativecommons.org/about/cc0

**Comment by felixrabe** [comment]
I was just about to open the same issue :) See also https://news.ycombinator.com/item?id=8486422 for the related HN discussion.

**Comment by artob** [comment]
@ers35 : Tens of thousands of [projects on GitHub](https://github.com/search?o=desc&q=unlicense&ref=searchresults&s=indexed&type=Code&utf8=✓) use the Unlicense public domain dedication for this purpose: http://unlicense.org/

For situations warranting still more formality, there is indeed CC0. Many public domain authors, myself included, feel it is rather overkill, however. Much as most developers continue to prefer the short and sweet MIT license instead of, say, the Apache License that without question covers more legal ground, there remain, and will continue to remain, different approaches to the formality and rigamarole involved in publishing software unfettered by copyright.

Incidentally, it's interesting that you, too, were inspired by SQLite's public domain dedication; so was the Unlicense initiative. See [Dissecting the Unlicense: Software Freedom in Four Clauses and a Link](http://ar.to/2010/01/dissecting-the-unlicense).

You can take another page from SQLite: if someone isn't able to satisfy themselves with you giving your software away gratis and with no strings whatsoever attached, you could always sell them a one-off license. The author of SQLite charges [$1000](http://www.hwaci.com/sw/sqlite/prosupport.html) for the service of signing a piece of paper for megacorps whose legal departments are unable to grok the notion of the public domain. It's not a bad business model.

**Comment by ers35** [comment]
I chose CC0: 6047b1e
